# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc88ced8369da6c57b79057597081175800c907dc0ff947562ba8c3c47b044ae81305c8a7a9bfb673323ca36a256c1405c5dfcb4d34ad5d49f1deda99589eeaf

test:
  secret_key_base: 24c00f4a81cce4820bb5506181033a539e2db226fbec1a8e59e8da0346354f070e070e029b0fc38f57a59e4f1d16726931cc77130761603f1585bfc854574fc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
